### ISSUE TITLE
Feature: Expose how many hours are equally priced or better as the current price

### ISSUE THREAD

**Issue by sstriker** [klaasnicolaas/python-easyenergy#54]
When you know you have consumers that need to run over a timespan of multiple hours or you need to run the consumer multiple times in different hours, automation requires knowing how many hours are at the current price.

For example, say you need to run something 3 times during a day in different hours.  Then using (pseudo): `if hours_priced_equal_or_lower_usage <= 3: run_my_consumer()` would be true in the 3 cheapest hours of the day.

**Comment by klaasnicolaas** [comment]
I was a bit wondering what you can actually do with the value that is returned. It counts the number of times (hours) that the current price occurs + the times when the price is lower than the current.

But I don't really see how you will use it to consume energy on the best times, but you can probably tell me that 😄

**Comment by sstriker** [comment]
I was going to use it to know whether the current hour is in the N lowest priced hours: `hours_priced_equal_or_lower_usage <= N`, and use that in a trigger and/or condition.

**Comment by klaasnicolaas** [comment]
But don't you eventually need to know the timestamps instead of a counter?

**Comment by sstriker** [comment]
Let's take the test data as an example, and calculate `hours_priced_equal_or_lower_usage` for each hour.  If we are interested in the 4 cheapest hours in the 24h period, we need to look for `hours_priced_equal_or_lower_usage <= 4`.  We then don't actually need the timestamp, we only need to look at this value.

| timestamp | hours_priced_equal_or_lower_usage |
|---|---|
| 2022-12-28T23:00:00+00:00 | 6 |
| 2022-12-29T00:00:00+00:00 | 5 |
| **2022-12-29T01:00:00+00:00** | **3** |
| **2022-12-29T02:00:00+00:00** | **1** |
| **2022-12-29T03:00:00+00:00** | **2** |
| **2022-12-29T04:00:00+00:00** | **4** |
| 2022-12-29T05:00:00+00:00 | 7 |
| 2022-12-29T06:00:00+00:00 | 8 |
| 2022-12-29T07:00:00+00:00 | 10 |
| 2022-12-29T08:00:00+00:00 | 13 |
| 2022-12-29T09:00:00+00:00 | 18 |
| 2022-12-29T10:00:00+00:00 | 17 |
| 2022-12-29T11:00:00+00:00 | 15 |
| 2022-12-29T12:00:00+00:00 | 13 |
| 2022-12-29T13:00:00+00:00 | 14 |
| 2022-12-29T14:00:00+00:00 | 20 |
| 2022-12-29T15:00:00+00:00 | 19 |
| 2022-12-29T16:00:00+00:00 | 23 |
| 2022-12-29T17:00:00+00:00 | 24 |
| 2022-12-29T18:00:00+00:00 | 22 |
| 2022-12-29T19:00:00+00:00 | 21 |
| 2022-12-29T20:00:00+00:00 | 16 |
| 2022-12-29T21:00:00+00:00 | 11 |
| 2022-12-29T22:00:00+00:00 | 9 |

Does that explain?  Or does it expose a flaw in my logic or assumptions? ;-)

**Comment by klaasnicolaas** [comment]
It is now clear to me and I understand what the intention is 😄

**Comment by klaasnicolaas** [comment]
I'm going to create a release soon and then I'll also close this issue, what might be interesting is to also make the changes in this python package: https://github.com/klaasnicolaas/python-energyzero

**Comment by sstriker** [comment]
I can have a go at porting it as you suggest, but feel free to run with it if I don't get to it.
